-- MySQL Script generated by MySQL Workbench
-- Sat Jun  8 10:20:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS mydb;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Igreja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Igreja` (
  `idIgreja` INT AUTO_INCREMENT,
  `localizacao` VARCHAR(45) NOT NULL,
  `dataFundacao` date,
  `nome`VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIgreja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membro` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `dataBatismo` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `naturalidade`VARCHAR(45) NOT NULL,
  `Igreja_idIgreja` INT NOT NULL,
  `disciplinado` INT NOT NULL,
  `idDisciplina` INT,
  `desligado` INT NOT NULL,
  `idDesligamento` INT,
  `cargo` VARCHAR(45) NOT NULL,
  `idConsagracao`INT,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Membro_Igreja_idx` (`Igreja_idIgreja` ASC),
  CONSTRAINT `fk_Membro_Igreja`
    FOREIGN KEY (`Igreja_idIgreja`)
    REFERENCES `mydb`.`Igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina`(
	`id` INT AUTO_INCREMENT,
    `dataInicio` DATE NOT NULL,
    `dataFim` DATE NOT NULL,
    `cpf` VARCHAR(16) NOT NULL,
    `dsc` VARCHAR(45) NOT NULL,
    `idIgreja` INT NOT NULL,
    CONSTRAINT FOREIGN KEY(`idIgreja`) REFERENCES Igreja(`idIgreja`),
    CONSTRAINT FOREIGN KEY(`cpf`) REFERENCES `mydb`.`Membro`(`cpf`),
    PRIMARY KEY(`id`))
    ENGINE = InnoDB
    DEFAULT CHARSET= utf8;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Igreja_idIgreja` INT NOT NULL,
  `modoUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf`VARCHAR(16) NOT NULL,
  `dataRegistro`DATE NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_Usuario_Igreja1_idx` (`Igreja_idIgreja` ASC),
  CONSTRAINT `fk_Usuario_Igreja1`
    FOREIGN KEY (`Igreja_idIgreja`)
    REFERENCES `mydb`.`Igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Consagração`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consagracao` (
  `id` INT NOT NULL auto_increment,
  `dsc` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dataConsagracao` DATE NOT NULL,
  `dataRegistro` DATE NOT NULL,
  `idIgreja` INT NOT NULL,
  CONSTRAINT FOREIGN KEY(`idIgreja`) REFERENCES Igreja(`idIgreja`),
  CONSTRAINT FOREIGN KEY(`cpf`) REFERENCES `mydb`.`membro`(`cpf`),
  PRIMARY KEY(`id`))
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
  
-- -----------------------------------------------------
-- Table `mydb`.`Desligamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desligamento` (
	`id` INT AUTO_INCREMENT,
	`cpf` VARCHAR(16) NOT NULL,
	`data` DATE NOT NULL,
    `dataRegistro` DATE NOT NULL,
	`dsc` VARCHAR(90) NOT NULL,
    `idIgreja` INT NOT NULL,
    CONSTRAINT FOREIGN KEY(`idIgreja`) REFERENCES Igreja(`idIgreja`),
	CONSTRAINT FOREIGN KEY(`cpf`) REFERENCES Membro(`cpf`),
	PRIMARY KEY(`id`))	
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

-- -----------------------------------------------------
-- Table `mydb`.`Setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setores`(
	idSetor INT AUTO_INCREMENT,
    nomeSe varchar(45),
    dataRegistroSe DATE,
    dscSe VARCHAR(90),
    idIgreja INT NOT NULL,
    CONSTRAINT FOREIGN KEY(idIgreja) REFERENCES Igreja(idIgreja),
    PRIMARY KEY(idSetor))
	ENGINE = INNODB
    DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Caixa`(
	idCaixa INT AUTO_INCREMENT,
    nomeCx VARCHAR(45) NOT NULL,
    idSetor INT NOT NULL,
    dataRegistroCx DATE NOT NULL,
    saldo FLOAT NOT NULL,
    dscCx  VARCHAR(90),
    CONSTRAINT FOREIGN KEY(idSetor) REFERENCES Setores(idSetor),
    PRIMARY KEY(idCaixa))
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Oferta`(
	idOferta INT AUTO_INCREMENT,
	valor FLOAT NOT NULL,
    idCaixa INT NOT NULL,
    dataOferta DATE NOT NULL,
    dscOferta VARCHAR(45),
    CONSTRAINT FOREIGN KEY(idCaixa) REFERENCES Caixa(idCaixa),
    PRIMARY KEY(idOferta))
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;
    
CREATE TABLE IF NOT EXISTS `mydb`.`Dizimo`(
	idDizimo INT AUTO_INCREMENT,
    valorDizimo FLOAT NOT NULL,
    idCaixa INT NOT NULL,
    cpfMembro VARCHAR(14),
    dataDizimo DATE NOT NULL,
    dscDizimo VARCHAR(90) NOT NULL,
    CONSTRAINT FOREIGN KEY(idCaixa) REFERENCES Caixa(idCaixa),
    CONSTRAINT FOREIGN KEY(cpfMembro) REFERENCES Membro(cpf),
    PRIMARY KEY(idDizimo))
    ENGINE = InnoDB
    DEFAULT CHARSET = Utf8;
    
    
CREATE TABLE IF NOT EXISTS `mydb`.`Despesa`(
    idDespesa INT AUTO_INCREMENT,
    valorDespesa FlOAT NOT NULL,
    idCaixa INT NOT NULL,
    dataDespesa DATE NOT NULL,
    dscDespesa VARCHAR(90) NOT NULL,
    CONSTRAINT FOREIGN KEY(idCaixa) REFERENCES Caixa(idCaixa),
    PRIMARY KEY(idDespesa))
    ENGINE = InnoDB
    DEFAULT CHARSET =utf8;
    

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO Igreja(localizacao,dataFundacao,nome) VALUES("MATRIZ",curdate(),"MATRIZ");
INSERT INTO usuario(login,senha,Igreja_idIgreja,modoUsuario,nome,cpf,dataRegistro) VALUES ('admin','admin',1,5,'kaio','admin',curdate());
INSERT INTO Setores(nomeSe,dataRegistroSe,dscSe,idIgreja) VALUES('Principal Matriz',curdate(),'Matriz',1);
INSERT INTO Caixa(nomeCx,idSetor,dataRegistroCx,saldo,dscCx) VALUES('Principal Matriz',1,curdate(),0,'Caixa Matriz');
